from typing import Any, Protocol


class QuestionRepository(Protocol):
    def get_stats(self) -> dict: ...

    def get_existing_topics(self, limit: int = 100) -> list[str]: ...

    def list_topic_subtopics(self, limit: int = 400) -> Any: ...

    def get_recent_topic_color(self, topic: str) -> str | None: ...

    def get_generation_context_questions(
        self,
        topic: str,
        subtopic: str | None = None,
        limit: int = 120,
    ) -> list[str]: ...

    def get_due_question(
        self,
        topics: list[str] | None = None,
        subtopics: list[tuple[str, str]] | None = None,
        randomize: bool = False,
        exclude_question_id: int | None = None,
    ) -> Any: ...

    def get_question_by_id(self, question_id: int) -> Any: ...

    def get_next_upcoming(
        self,
        topics: list[str] | None = None,
        subtopics: list[tuple[str, str]] | None = None,
    ) -> Any: ...

    def get_recent_questions(self, limit: int = 10) -> Any: ...

    def list_questions(self, limit: int = 200) -> Any: ...

    def list_topics_with_stats(self, limit: int = 200) -> Any: ...

    def list_subtopics_with_stats(self, topic: str | None = None, limit: int = 400) -> Any: ...

    def list_questions_by_topic(self, topic: str, limit: int = 400) -> Any: ...

    def list_questions_by_subtopic(self, topic: str, subtopic: str, limit: int = 400) -> Any: ...

    def update_question(
        self,
        question_id: int,
        *,
        text: str,
        topic: str | None,
        subtopic: str | None,
    ) -> bool: ...

    def delete_question(self, question_id: int) -> bool: ...

    def rename_topic(self, topic: str, new_topic: str) -> int: ...

    def delete_topic(self, topic: str) -> int: ...

    def rename_subtopic(self, topic: str, subtopic: str, new_subtopic: str) -> int: ...

    def delete_subtopic(self, topic: str, subtopic: str) -> int: ...


class FeedbackRepository(Protocol):
    def get_latest_feedback(self, question_id: int) -> Any: ...

    def save_feedback(self, question_id: int, user_answer: str, result: dict) -> None: ...
